version: '3'

services:
  db:
    image: mysql:latest

    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS

    ports:
      - "3306:3306"

  # web:
  #   build: .

  #   volumes:
  #     - .:/backend

  #   ports:
  #     - "8000:8000"